### ISSUE TITLE
Just started the basic integration

### ISSUE THREAD

**Issue by farhan-syed** [masteringmodernpayments/book#16]
so i do the command  `createuser -s sales` 
and i get this in return 
`createuser: creation of new role failed: ERROR:  role "sales" already exists`

**Comment by peterkeen** [comment]
Should be safe to ignore. Just skip that and go to the next command.

**Comment by farhan-syed** [comment]
also do i start postgres when i do this basic integration?

**Comment by farhan-syed** [comment]
after i do `rails generate devise:install` and then run `rake db:migrate` i get all this: 

== 20150616221459 DeviseCreateUsers: migrating ================================
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "users" already exists
: CREATE TABLE "users" ("id" serial primary key, "email" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "remember_created_at" timestamp, "sign_in_count" integer DEFAULT 0 NOT NULL, "current_sign_in_at" timestamp, "last_sign_in_at" timestamp, "current_sign_in_ip" inet, "last_sign_in_ip" inet, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL) /Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in`block in execute'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in`execute'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:662:in`block in method_missing'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in`say_with_time'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/Users/FarhanSyed/sales/db/migrate/20150616221459_devise_create_users.rb:3:in`change'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:606:in `exec_migration'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in`block (2 levels) in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in `block in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in`with_connection'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:765:in`migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in`block in ddl_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in`within_new_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/transactions.rb:220:in`transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:994:in`execute_migration_in_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:956:in `block in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in`each'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in`up'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in`migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "users" already exists
: CREATE TABLE "users" ("id" serial primary key, "email" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "remember_created_at" timestamp, "sign_in_count" integer DEFAULT 0 NOT NULL, "current_sign_in_at" timestamp, "last_sign_in_at" timestamp, "current_sign_in_ip" inet, "last_sign_in_ip" inet, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL) 
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in`async_exec'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in`block in log'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in`log'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in`create_table'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in`block in say_with_time'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `say_with_time'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in`method_missing'
/Users/FarhanSyed/sales/db/migrate/20150616221459_devise_create_users.rb:3:in `change'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:606:in`exec_migration'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in`block in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in`migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:765:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:995:in`block in execute_migration_in_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in`block in transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in`transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/transactions.rb:220:in `transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in`ddl_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:956:in`block in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `each'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in`migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in `up'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in`migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in`block (2 levels) in <top (required)>'
PG::DuplicateTable: ERROR:  relation "users" already exists
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in`block in execute'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in`execute'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:662:in`block in method_missing'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in`say_with_time'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/Users/FarhanSyed/sales/db/migrate/20150616221459_devise_create_users.rb:3:in`change'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:606:in `exec_migration'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in`block (2 levels) in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in `block in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in`with_connection'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:765:in`migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in`block in ddl_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in`within_new_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/transactions.rb:220:in`transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:994:in`execute_migration_in_transaction'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:956:in `block in migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in`each'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:952:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:820:in`up'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/migration.rb:798:in `migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:137:in`migrate'
/Users/FarhanSyed/.gem/ruby/2.2.2/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by peterkeen** [comment]
Seems like maybe it has partially run this stuff at least once before. You could try db:reset which will completely destroy and recreate the database.
